baseURL = "/"
locale = "en-us"
relativeURLs = true
publishDir = "docs"
title = "Manya Bansal"
copyright = "Manya Bansal"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications/"
weight = 2

[[menu.main]]
name = "Posters"
url = "/posters/"
weight = 3

[[menu.main]]
name = "Talks"
url = "/talks/"
weight = 4

[[menu.main]]
name = "Teaching"
url = "/teaching/"
weight = 5

[[menu.main]]
name = "Personal"
url = "/personal/"
weight = 6

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  profilePicture = "images/my_photo_new.png"
  favicon = "images/raspberry-pi.png"
  description = """I'm a Member of Technical Staff at [humans&](https://humansand.ai/).

I'm currently on leave from my Ph.D. program at MIT, where I worked with [Saman Amarasinghe](https://groups.csail.mit.edu/commit/) and [Jonathan Ragan-Kelley](https://people.csail.mit.edu/jrk/) on programming languages for high performance computing.

My research is about helping programmers write fast, low-level GPU code that is still modular, reusable, and correct. I believe programming systems should give people precise control over hardware while making that control easier to compose and trust.

Before MIT, I was an undergraduate at Stanford, where I studied mathematics and received my B.S. in 2023. At Stanford, I was lucky to work with [Fredrik Kjolstad](http://fredrikbk.com/) and [Dawson Engler](https://web.stanford.edu/~engler/), who let me tinker and build many, many small things.
"""
